[general]
import = ["/home/aikixd/.config/alacritty/alacritty-theme/themes/citylights.toml"]

[terminal.shell]
program = "/bin/fish"

[window]
decorations = "none"
dynamic_padding = false

[font]
builtin_box_drawing = true

[font.normal]
family = "BitstromWera Nerd Font"

[bell]
animation = "Linear"
color = "#d0a044"
duration = 300

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[[keyboard.bindings]]
chars = "\u001B[105;5u"
key = "I"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[112;6u"
key = "P"
mods = "Control | Shift"

[[keyboard.bindings]]
chars = "\u001B[117;6u"
key = "U"
mods = "Control | Shift"

[terminal]

